version: '3.1'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'sebasttiandaza'
      MYSQL_PASSWORD: 'sebastianDaza100/#'
      MYSQL_VERSION: '5.7'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: